# Generated by Django 3.2.6 on 2025-09-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='days',
            old_name='unavailable_days',
            new_name='available_recurring_days',
        ),
    ]
